name: CI

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e .[dev]
      - name: Lint
        run: |
          ruff check .
          black --check .
      - name: Test with coverage
        run: |
          pytest
          if [ "${{ matrix.python-version }}" = "3.12" ]; then
            coverage-badge -o coverage.svg -f
          fi
      - name: Commit coverage badge (main only)
        if: matrix.python-version == '3.12' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add coverage.svg || true
          git commit -m "Update coverage badge [skip ci]" || echo "No changes"
          git push || true